[package]
name = "arigato"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
itertools = "0.13.0"
phf = { version = "0.11.2", features = ["macros"] }
